#!/usr/bin/env python3
"""Generate Jak II AOT inventories twice and compare every generated byte."""

import filecmp
import os
from pathlib import Path
import shutil
import subprocess
import tempfile


def main() -> int:
    generator = os.environ.get("AOT_GENERATOR")
    source_root = os.environ.get("AOT_SOURCE_ROOT")
    target_triple = os.environ.get("AOT_TARGET_TRIPLE")
    if not generator or not source_root or not target_triple:
        raise SystemExit("AOT_GENERATOR, AOT_SOURCE_ROOT and AOT_TARGET_TRIPLE are required")

    with tempfile.TemporaryDirectory(prefix="opengoal-aot-determinism-") as temporary:
        root = Path(temporary)
        first = root / "first"
        second = root / "second"
        command = [generator, "--source-root", source_root, "--target-triple", target_triple]
        subprocess.run([*command, "--output-dir", str(first)], check=True)
        subprocess.run([*command, "--output-dir", str(second)], check=True)
        first_files = sorted(path.relative_to(first) for path in first.rglob("*"))
        second_files = sorted(path.relative_to(second) for path in second.rglob("*"))
        if first_files != second_files:
            raise SystemExit("AOT generation produced different file lists")
        for relative in first_files:
            left = first / relative
            right = second / relative
            if not left.is_file() or not right.is_file() or not filecmp.cmp(left, right, shallow=False):
                raise SystemExit(f"AOT generation is not deterministic: {relative}")
        print(f"PASS: deterministic AOT generation ({len(first_files)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
